{% set name = "Orange3-Prototypes" %}
{% set version = "0.21.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 552b78f7ab112dfe42c05231d54591e5ff4e76746e14a82ad670681744294a1d

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.8
    - pip
  run:
    - python >=3.8
    - Orange3 >=3.34
    - numpy >=1.19.5
    - scipy >=1.9.0
    - scikit-learn >=1.0.1
    - pyqtgraph
    - AnyQt >=0.1.0
    - pandas >=1.3.0
    - openai >=1.0.0
    - tiktoken

test:
  imports:
    - orangecontrib.prototypes

about:
  home: https://orangedatamining.com/
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Addon with widgets which are still prototypes
  description: |
    Addon with widgets which are still prototypes. Only for the brave.
  doc_url: https://readthedocs.org/projects/orange3-prototypes/
  dev_url: https://github.com/biolab/orange3-prototypes

extra:
  recipe-maintainers:
    - primozgodec
    - markotoplak
    - ajdapretnar
    - vesnat
